In [4]:
from sys import argv
import pandas as pd
import numpy as np

In [1]:
def calc_proba(valuesN, w, b):
	m, n = valuesN.shape
	proba = np.zeros(m)
	for i in range(m):
		z = np.dot(w, valuesN.iloc[i].values) + b
		proba[i] = 1 / (1 + np.exp(-z))
	return proba

In [2]:
def normalize_value(df_test, df_result):
	test_N = df_test.copy()

	for i in range(len(df_test.columns)):
		mean = df_result.loc["Mean", df_test.columns[i]]
		std = df_result.loc["Std", df_test.columns[i]]
		test_N.loc[:, test_N.columns[i]] = (test_N.loc[:, test_N.columns[i]] - mean) / std
	return (test_N)

In [5]:
df_toTest = pd.read_csv("../datasets/dataset_test.csv", index_col = "Index")

In [11]:
params = pd.read_csv("../params.csv", index_col=0)

In [12]:
params.columns

,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Charms,Flying,b
Index,,,,,,,,,,,
Mean,1.141020,-0.387863,3.153910,-224.589915,495.747970,2.963095,1030.096946,5.950373,-243.374409,21.958012,NaN
Std,5.218016,5.211132,4.153970,486.189433,106.251202,4.424353,44.111025,3.146852,8.780895,97.601087,NaN
Slytherin,-0.894681,1.071689,-1.695363,-0.396658,-0.538759,-0.061856,0.387140,0.713709,-0.530763,-0.477730,-3.192161
Ravenclaw,0.462051,1.118071,0.144250,1.416851,1.054494,0.085048,0.110737,-0.202494,1.072528,-0.205490,-2.222858
Gryffindor,-0.911898,-0.295941,0.561723,-0.179831,0.876162,-0.843591,-1.042166,0.009811,-0.318203,0.980681,-2.658454
Hufflepuff,1.442905,-1.941509,0.891583,-0.944795,-1.477237,0.856084,0.647798,-0.513191,-0.300118,-0.387274,-1.952781

In [13]:
df_toTest

,Hogwarts House,First Name,Last Name,Birthday,Best Hand,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
Index,,,,,,,,,,,,,,,,,,
0,NaN,Rico,Sargent,2001-10-06,Right,41642.0,696.096071,3.020172,-6.960961,7.996,-365.151850,393.138185,4.207691,1046.742736,3.668983,0.373853,-244.48172,-13.62
1,NaN,Tamara,Shackelford,1998-01-08,Left,45352.0,-370.844655,2.965226,3.708447,6.349,522.580486,602.853051,6.460017,1048.053878,8.514622,0.577432,-231.29200,-26.26
2,NaN,Staci,Crandall,1998-09-15,Left,43502.0,320.303990,-6.185697,-3.203040,4.619,-630.073207,588.071795,-5.565818,936.437358,1.850829,-1.647150,-252.99343,200.15
3,NaN,Dee,Gavin,2001-05-10,Right,61831.0,407.202928,4.962442,NaN,NaN,-449.179806,427.699966,NaN,1043.397718,4.656573,1.164708,-244.01660,-11.15
4,NaN,Gregory,Gustafson,1999-02-01,Right,NaN,288.337747,3.737656,-2.883377,4.886,-449.732166,385.712782,2.876347,1051.377936,2.750586,0.102104,-243.99806,-7.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,NaN,Maria,Kidwell,1999-02-06,Left,45857.0,-554.181932,-5.647655,5.541819,-3.799,-591.764651,392.973420,7.048482,1047.648405,10.408749,1.882786,-248.39978,-94.89
396,NaN,Frederic,Koonce,1997-11-11,Left,51842.0,632.233530,6.754862,-6.322335,3.294,-221.848397,319.360250,3.921402,1035.681313,-0.169741,-1.074303,-246.87982,-15.53
397,NaN,Eugene,Peralta,1998-11-14,Right,61982.0,292.108738,5.234530,-2.921087,4.230,-787.036050,433.259967,3.898160,1069.794110,6.495579,-2.286537,-244.01333,1.25
398,NaN,Allan,Bentley,1998-10-13,Left,56020.0,-726.418553,6.735582,7.264186,3.908,511.960762,613.391514,7.244499,1042.058804,7.554259,-0.788817,-228.24290,-18.27
399,NaN,Clarence,Pope,1999-07-26,Left,46452.0,-735.939727,7.224872,NaN,2.889,NaN,513.457470,3.095942,1035.331589,0.477165,0.975627,-230.70067,-8.78

In [14]:
col_to_del = [col for col in df_toTest.columns if col not in params.columns]

In [16]:
X_toTest = df_toTest.drop(col_to_del, axis=1, inplace=False)

In [17]:
# Replace missing values with the mean of the feature
for i in range(len(X_toTest.columns)):
	X_toTest.loc[X_toTest.iloc[:,i].isna(), X_toTest.columns[i]] = params.loc["Mean", X_toTest.columns[i]]

In [38]:
def create_prob_arr(df_test, params):
	result = df_test.copy()
	normalized_val = normalize_value(result, params)
	result.loc[:, "Slytherin"] = calc_proba(normalized_val, params.iloc[2, :-1], params.iloc[2, -1]) * 100
	result.loc[:, "Ravenclaw"] = calc_proba(normalized_val, params.iloc[3, :-1], params.iloc[3, -1]) * 100
	result.loc[:, "Gryffindor"] = calc_proba(normalized_val, params.iloc[4, :-1], params.iloc[4, -1]) * 100
	result.loc[:, "Hufflepuff"] = calc_proba(normalized_val, params.iloc[5, :-1], params.iloc[5, -1]) * 100
	return result

In [40]:
prob_array = create_prob_arr(X_toTest, params)

,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Charms,Flying,Slytherin,Ravenclaw,Gryffindor,Hufflepuff
Index,,,,,,,,,,,,,,
0,3.020172,-6.960961,7.99600,-365.151850,393.138185,4.207691,1046.742736,3.668983,-244.48172,-13.62,0.173497,1.020712,2.393977,99.176558
1,2.965226,3.708447,6.34900,522.580486,602.853051,6.460017,1048.053878,8.514622,-231.29200,-26.26,0.722306,97.571886,1.512259,0.717992
2,-6.185697,-3.203040,4.61900,-630.073207,588.071795,-5.565818,936.437358,1.850829,-252.99343,200.15,0.563300,0.460733,99.714690,0.288139
3,4.962442,-0.387863,3.15391,-449.179806,427.699966,2.963095,1043.397718,4.656573,-244.01660,-11.15,3.574541,4.284370,1.175078,74.002577
4,3.737656,-2.883377,4.88600,-449.732166,385.712782,2.876347,1051.377936,2.750586,-243.99806,-7.12,1.127769,1.845745,1.304553,95.204660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,-5.647655,5.541819,-3.79900,-591.764651,392.973420,7.048482,1047.648405,10.408749,-248.39978,-94.89,99.210389,1.194644,0.356719,1.174446
396,6.754862,-6.322335,3.29400,-221.848397,319.360250,3.921402,1035.681313,-0.169741,-246.87982,-15.53,0.408138,0.938036,0.485695,99.704635
397,5.234530,-2.921087,4.23000,-787.036050,433.259967,3.898160,1069.794110,6.495579,-244.01333,1.25,2.990119,1.017430,0.909319,95.667389
398,6.735582,7.264186,3.90800,511.960762,613.391514,7.244499,1042.058804,7.554259,-228.24290,-18.27,1.222740,99.449481,0.488075,0.308910
399,7.224872,-0.387863,2.88900,-224.589915,513.457470,3.095942,1035.331589,0.477165,-230.70067,-8.78,0.240012,61.373415,1.050189,52.757707

In [44]:
def create_house_sheet(prob_array):
	df_array = prob_array.copy()
	last_columns = df_array.iloc[:, -4:]
	nameHouses = last_columns.idxmax(axis=1)
	df_array["Hogwarts House"] = nameHouses
	df_finals = pd.DataFrame(df_array.iloc[:, -1:])
	return df_finals

In [45]:
df_finals = create_house_sheet(prob_array)

In [46]:
df_finals.to_csv("houses.csv")